plugins {
    id 'base'

    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.jooq.docker) apply false
}

group = 'com.packing'
version = '1.0.0' // x-release-please-version
description = '3d-packing-backend'

subprojects {
    apply plugin: 'java-library'

    group = rootProject.group
    version = rootProject.version

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    dependencies {
        ['api', 'implementation', 'compileOnly', 'annotationProcessor', 'runtimeOnly',
         'testImplementation', 'testCompileOnly', 'testAnnotationProcessor', 'testRuntimeOnly'
        ].each { conf ->
            add(conf, platform(libs.spring.boot.bom))
            add(conf, platform(libs.spring.cloud.azure.bom))
        }

        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
        testCompileOnly 'org.projectlombok:lombok'
        testAnnotationProcessor 'org.projectlombok:lombok'

        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    plugins.withId('java-test-fixtures') {
        dependencies {
            testFixturesApi platform(libs.spring.boot.bom)
            testFixturesApi platform(libs.spring.cloud.azure.bom)
            testFixturesAnnotationProcessor platform(libs.spring.boot.bom)
            testFixturesCompileOnly 'org.projectlombok:lombok'
            testFixturesAnnotationProcessor 'org.projectlombok:lombok'
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs << '-parameters'
    }

    tasks.named('test') {
        useJUnitPlatform()
        testLogging {
            events 'passed', 'skipped', 'failed'
            exceptionFormat = 'full'
        }
    }
}
