spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:packing}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
firebase.project-id=${FIREBASE_PROJECT_ID:packing-3d-6a9e6}
firebase.service-account=${FIREBASE_SERVICE_ACCOUNT_B64:}
firebase.admin-enabled=${FIREBASE_ADMIN_ENABLED:true}

spring.cloud.azure.storage.blob.connection-string=${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;}

app.storage.sas-mode=${STORAGE_SAS_MODE:ACCOUNT_KEY}
app.storage.enabled=${STORAGE_ENABLED:true}