spring.cloud.azure.keyvault.secret.property-sources[0].name=packing-kv
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://packing-kv.vault.azure.net/

spring.cloud.azure.credential.managed-identity-enabled=true

spring.datasource.url=jdbc:postgresql://${db.endpoint}:${DB_PORT:5432}/${DB_NAME:packing}?sslmode=require
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

firebase.project-id=${firebase.project.id}
firebase.service-account=${firebase.service.account}
