description = 'Application layer: application services, commands/results, output ports.'

dependencies {
    api project(':domain')

    api 'org.springframework:spring-tx'
    api 'org.springframework:spring-context'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
}
